ignore:
  - db/migrate/**/*
  - db/sample_data.rb
  - db/sample_data/**/*
  - config/environments/*.rb
  - spec/rails_helper.rb
  - spec/spec_helper.rb

plugins:
  - standard-rails:
      target_rails_version: 8.1
