name: Test Permissions

on:
  workflow_dispatch:  # Manual trigger for testing

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Test issue creation
        run: |
          gh issue create \
            --title "Test: Permissions Check" \
            --body "Testing GitHub Actions permissions configuration. This issue can be closed immediately." \
            --label "type: chore"
        env:
          GH_TOKEN: ${{ github.token }}

